import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Lista de tareas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

  
        <div className="flex flex-col min-h-screen">{children}</div>

  );
}

